name: update song data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: ./update.sh ${{ secrets.IPATOOL_USERNAME }} ${{ secrets.IPATOOL_PASSWORD }}
      
      - name: Get Phigros version
        id: version
        run: echo "version=$(cat .phigros-version)" >> "$GITHUB_OUTPUT"
      
      - name: Commit if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: songs.json .phigros-version
          default_author: github_actions
          message: "Phigros ${{ steps.version.outputs.version }}"
