name: update song data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 * * 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run
        id: update
        run: |
          cp .phigros-version .phigros-version-old
          
          ./update.sh ${{ secrets.IPATOOL_USERNAME }} ${{ secrets.IPATOOL_PASSWORD }}

          set +e
          cmp -s .phigros-version-old .phigros-version
          echo "updated=$?" >> "$GITHUB_OUTPUT"
          echo "version=$(cat .phigros-version)" >> "$GITHUB_OUTPUT"
          set -e
          
          rm .phigros-version-old
      
      - name: Commit if changed
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.update.outputs.updated == '1' }}
        with:
          add: songs.json .phigros-version
          tag: "v${{ steps.update.outputs.version }}"
          default_author: github_actions
          message: "Phigros ${{ steps.update.outputs.version }}"
